services:
  mysql:
    image: mysql:8.0
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kysely_test
    command: ["--default-authentication-plugin=mysql_native_password"]
